### ISSUE TITLE
Current status?

### ISSUE THREAD

**Issue by swelham** [joshnuss/commerce_billing#6]
Hi @joshnuss, we have just started up a [missing packages and ideas thread](https://elixirforum.com/t/missing-libraries-and-tools/2179) on the elixir forum and an initial idea is PayPal integration.

One of the members pointed me into the direction of your repo as your road map includes this, so I just wanted to check in with you and find out what your plans are for this?

The thread is also aiming to help find extra contributers as well to help along larger and more complex projects.

**Comment by joshnuss** [comment]
Hey @swelham,

Yes, totally agree it would be a great feature to add.

The goal is to support as many gateways as possible, So far it has the basic abstractions and Stripe support. In the future I hope it will have many more gateways - may even add some myself (as the need arises).

If you do write a PayPal gateway, please open a PR and I'll merge it in.

Cheers!

**Comment by swelham** [comment]
:+1:  Excellent! I have added this repo to the thread and listed it as looking for help, so hopefully we can find some people (if not myself) to start working with you on this.

**Comment by joshnuss** [comment]
Thanks @swelham! Any help would be greatly appreciated
