### ISSUE TITLE
Changing JSON lib

### ISSUE THREAD

**Issue by swelham** [joshnuss/commerce_billing#8]
Hi again @joshnuss 

I have finally got around to opening this project and just ran test and saw some warnings about Jazz. This lib looks to be unmaintained and is currently targeting Elixir 1.0.0-rc1. Do you have any issue if I change this for something such as [poison](https://github.com/devinus/poison)?

Just in case you are happy with this, I have create PR #9, if not let me know.

**Comment by joshnuss** [comment]
Sounds good to me! Thanks @swelham!
